name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Mount npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm|${{ runner.os }}|node:${{ matrix.node-version }}|package:${{ hashFiles('package.json') }}
          restore-keys: |
            npm|${{ runner.os }}|node:${{ matrix.node-version }}|package:
            npm|${{ runner.os }}|node:
            npm|${{ runner.os }}|

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      - name: Initialize empty secrets
        run: echo '{}' > secrets.json
      - name: Lint Fido
        run: cli/fido.js lint
      - name: Build Fido
        run: cli/fido.js build --env production
      - name: Build DevServer
        run: cli/fido.js build --env production --dev-server
      - name: Build Server
        run: cli/fido.js build-server --env production
